# Example Site settings
header_pages:
  - index.md
  - about.md
  - wo.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'
baseurl: /mhl-abschlusskonzert

plugins:
  - jekyll-seo-tag

# Theme options
# style: dark # dark (default) or light or hacker
# listen_for_clients_preferred_style: true # true or false (default)

# Fonts
# disable_google_fonts: false # set true to prevent loading fonts.googleapis.com

# Allow inline scripts for the language toggle
csp_extra: "script-src 'self' 'unsafe-inline';"
